# Generated by Django 3.2.19 on 2023-08-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230819_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='bole', max_length=150, verbose_name='Nearest Location'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='bole', max_length=13, verbose_name='phone'),
        ),
    ]
