# Generated by Django 3.2.19 on 2023-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230822_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Brand Title')),
                ('slug', models.SlugField(max_length=55, verbose_name='Brand Slug')),
                ('description', models.TextField(blank=True, verbose_name='Brand Description')),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brand', verbose_name='Brand Image')),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('is_featured', models.BooleanField(verbose_name='Is Featured?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ('-created_at',),
            },
        ),
    ]
