# Generated by Django 3.2.19 on 2023-09-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='active_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.PositiveBigIntegerField(default=None, help_text='discount in percentage'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default=None),
        ),
    ]
