# Generated by Django 3.2.19 on 2023-09-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.PositiveBigIntegerField(default=None, help_text='Discount in percentage'),
        ),
    ]
