# Generated by Django 3.2.19 on 2023-09-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.TextField(default=None, max_length=40, unique=True),
        ),
    ]
