# Generated by Django 3.2.9 on 2024-05-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
