# Generated by Django 5.0.6 on 2025-02-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Sold Out?'),
        ),
    ]
