# Generated by Django 5.2.3 on 2025-06-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_cart_size_order_size_product_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price at Purchase'),
        ),
    ]
