# Generated by Django 3.2.3 on 2026-03-10 17:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_affiliatecommission_payout_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150)),
                ('product_sku', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('customer_full_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_city', models.CharField(max_length=150)),
                ('customer_address', models.CharField(max_length=255)),
                ('telegram_chat_id', models.CharField(db_index=True, max_length=40)),
                ('telegram_username', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_orders', to='store.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='telegrambotorder',
            index=models.Index(fields=['status', 'created_at'], name='store_teleg_status_e055c5_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambotorder',
            index=models.Index(fields=['telegram_chat_id', 'created_at'], name='store_teleg_telegra_867532_idx'),
        ),
    ]
