# Generated by Django 3.2.3 on 2026-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20260310_1701'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='affiliateclick',
            name='store_affil_affilia_694f34_idx',
        ),
        migrations.RemoveIndex(
            model_name='affiliateclick',
            name='store_affil_session_f5e643_idx',
        ),
        migrations.RemoveIndex(
            model_name='affiliateclick',
            name='store_affil_convert_73ab73_idx',
        ),
        migrations.RemoveIndex(
            model_name='affiliatecommission',
            name='store_affil_affilia_8c08c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='affiliatecommission',
            name='store_affil_order_i_5f1c0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='affiliateprofile',
            name='store_affil_is_acti_3bb16d_idx',
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['affiliate', 'created_at'], name='store_affil_affilia_aa40da_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['session_key', 'created_at'], name='store_affil_session_cfbcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['converted', 'created_at'], name='store_affil_convert_d94356_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['affiliate', 'status', 'created_at'], name='store_affil_affilia_460bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['order', 'created_at'], name='store_affil_order_i_598e19_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['is_active', 'created_at'], name='store_affil_is_acti_1d4c01_idx'),
        ),
    ]
