# Generated by Django 6.0 on 2026-04-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_productreview_restockrequest_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_notes',
            field=models.TextField(blank=True, verbose_name='Care Notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=180, verbose_name='Delivery Note'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_notes',
            field=models.TextField(blank=True, verbose_name='Fit Notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=120, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_note',
            field=models.CharField(blank=True, max_length=180, verbose_name='Return Note'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Quantity'),
        ),
    ]
