# Generated by Django 6.0 on 2026-04-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_product_care_notes_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_inventory', to='store.product')),
            ],
            options={
                'ordering': ('size',),
                'indexes': [models.Index(fields=['product', 'size'], name='store_produ_product_848b76_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size_inventory')],
            },
        ),
    ]
