# Generated by Django 6.0 on 2026-04-11 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_productsizestock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAIDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, verbose_name='Source SKU')),
                ('vendor_hint', models.CharField(blank=True, max_length=120, verbose_name='Vendor Hint')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='ai-reference', verbose_name='Identifier Image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=250)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('source_links', models.JSONField(blank=True, default=list)),
                ('image_plan', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ai_drafts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='store.product')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'indexes': [models.Index(fields=['created_by', 'updated_at'], name='store_produ_created_ee2fcb_idx'), models.Index(fields=['product', 'updated_at'], name='store_produ_product_f1eb90_idx'), models.Index(fields=['sku', 'updated_at'], name='store_produ_sku_5e03c5_idx'), models.Index(fields=['status', 'updated_at'], name='store_produ_status_e8725a_idx')],
            },
        ),
    ]
