# Generated by Django 6.0 on 2026-04-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_productaidraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAIDraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai-generated', verbose_name='Generated Candidate Image')),
                ('shot_name', models.CharField(max_length=120)),
                ('prompt', models.TextField(blank=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='store.productaidraft')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['draft', 'sort_order'], name='store_produ_draft_i_d94db5_idx')],
            },
        ),
    ]
