# Generated by Django 6.0 on 2026-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_productaidraftimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=180, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='productaidraft',
            name='generator_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productaidraft',
            name='secondary_reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai-reference', verbose_name='Secondary Reference Image'),
        ),
        migrations.AddField(
            model_name='productaidraft',
            name='seo_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
