# Generated by Django 3.2.3 on 2026-04-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_product_image_alt_text_product_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaidraft',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productaidraft',
            name='last_error_stage',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productaidraft',
            name='pipeline_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('analyzing', 'Generating Copy'), ('generating_images', 'Generating Images'), ('ready', 'Ready'), ('manual_review', 'Manual Review')], default='idle', max_length=30),
        ),
        migrations.AddField(
            model_name='productaidraft',
            name='processing_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productaidraft',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productaidraft',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='productaidraft',
            index=models.Index(fields=['created_by', 'pipeline_state', 'updated_at'], name='store_produ_created_34333a_idx'),
        ),
    ]
