# Generated by Django 3.2.3 on 2026-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_order_staff_notes_coupon_used_count_max_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('state', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram conversation state',
                'verbose_name_plural': 'Telegram conversation states',
            },
        ),
    ]
