# Generated by Django 4.2.21 on 2026-07-14 20:32

from django.db import migrations, models
import django.utils.timezone

DEFAULT_STOCK_PER_SIZE = 10


def backfill_size_inventory(apps, schema_editor):
    """Ensure every CSV size has a ProductSizeStock row before the column drops.

    The save()-time sync has normally kept these in step; this is the safety
    net for products edited outside that path.
    """
    Product = apps.get_model("store", "Product")
    ProductSizeStock = apps.get_model("store", "ProductSizeStock")

    for product in Product.objects.exclude(available_sizes="").exclude(available_sizes__isnull=True).iterator():
        existing = {
            (size or "").casefold()
            for size in ProductSizeStock.objects.filter(product=product).values_list("size", flat=True)
        }
        for chunk in (product.available_sizes or "").replace("\r", "\n").replace(",", "\n").split("\n"):
            value = " ".join(chunk.split()).strip()
            if not value or value.casefold() in existing:
                continue
            ProductSizeStock.objects.create(
                product=product,
                size=value,
                quantity=DEFAULT_STOCK_PER_SIZE,
            )
            existing.add(value.casefold())


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0049_backgroundtask"),
    ]

    operations = [
        migrations.RunPython(backfill_size_inventory, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="available_sizes",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="active_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.PositiveIntegerField(help_text="discount in percentage"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="expiry_date",
            field=models.DateField(),
        ),
    ]
