# Generated by Django 4.2.21 on 2026-07-14 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion




GUEST_USERNAME_PREFIX = "guest-"


def migrate_guest_users(apps, schema_editor):
    """Move guest-<session_key> auth_user rows onto session-keyed ownership.

    Orders keep their contact details in guest_contact; carts move to the
    session key; the placeholder users (and their cascading addresses) are
    then deleted.
    """
    User = apps.get_model("auth", "User")
    Address = apps.get_model("store", "Address")
    Cart = apps.get_model("store", "Cart")
    Order = apps.get_model("store", "Order")

    guests = User.objects.filter(username__startswith=GUEST_USERNAME_PREFIX)
    for guest in guests.iterator():
        session_key = guest.username[len(GUEST_USERNAME_PREFIX):][:64]
        latest_address = Address.objects.filter(user=guest).order_by("-id").first()
        full_name = f"{guest.first_name} {guest.last_name}".strip()
        contact = None
        if latest_address or full_name:
            contact = {
                "full_name": full_name,
                "phone": getattr(latest_address, "phone", "") or "",
                "city": getattr(latest_address, "city", "") or "",
                "address": getattr(latest_address, "address", "") or "",
            }
        Order.objects.filter(user=guest).update(user=None, session_key=session_key, guest_contact=contact)
        Cart.objects.filter(user=guest).update(user=None, session_key=session_key)
    guests.delete()


def restore_noop(apps, schema_editor):
    # Guest users are not recreated on rollback; orders/carts keep working
    # through their session_key/guest_contact columns.
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0050_remove_product_available_sizes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Guest Session Key",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_contact",
            field=models.JSONField(
                blank=True,
                help_text="full_name/phone/city/address captured at guest checkout",
                null=True,
                verbose_name="Guest Contact",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="Guest Session Key",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key", "updated_at"],
                name="store_cart_session_e18b31_idx",
            ),
        ),
            migrations.RunPython(migrate_guest_users, restore_noop),
    ]
