# Generated by Django 3.2.3 on 2026-07-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_cart_session_key_order_guest_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaidraft',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="Becomes the product's main image when the draft is turned into a product.", null=True, upload_to='ai-cover', verbose_name='Storefront Cover Image'),
        ),
        migrations.CreateModel(
            name='ProductAIDraftGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai-gallery', verbose_name='Gallery Upload')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_uploads', to='store.productaidraft')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='productaidraftgalleryimage',
            index=models.Index(fields=['draft', 'sort_order'], name='store_produ_draft_i_7d2b96_idx'),
        ),
    ]
