# Generated by Django 3.2.3 on 2026-07-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_ai_draft_cover_and_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaidraft',
            name='sizes',
            field=models.CharField(blank=True, default='', help_text='Comma-separated; applied to the product when the draft becomes one.', max_length=100, verbose_name='Sizes'),
        ),
    ]
