# Generated by Django 3.2.3 on 2026-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_productaidraft_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price shown struck through; the product is on sale while this is higher than the price.', max_digits=8, null=True, verbose_name='Compare-at Price'),
        ),
    ]
