# Generated by Django 3.2.3 on 2026-07-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0054_product_compare_at_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='task_type',
            field=models.CharField(choices=[('telegram_product_post', 'Telegram product post'), ('telegram_order_notify', 'Telegram order notification'), ('telegram_signup_notify', 'Telegram signup notification'), ('ai_enrich_draft', 'AI draft enrichment'), ('customer_order_confirm', 'Customer order confirmation'), ('customer_order_status', 'Customer order status update'), ('customer_restock_notify', 'Customer restock alert'), ('customer_abandoned_cart', 'Customer abandoned-cart nudge')], max_length=40),
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('chat_id', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=150)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('last_abandoned_nudge_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='telegramlink',
            index=models.Index(fields=['chat_id', 'updated_at'], name='store_teleg_chat_id_53dad6_idx'),
        ),
    ]
