# Generated by Django 3.2.3 on 2026-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_telegram_link_customer_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='fit_feedback',
            field=models.CharField(blank=True, choices=[('true_to_size', 'True to size'), ('runs_small', 'Runs small'), ('runs_large', 'Runs large')], default='', max_length=20, verbose_name='How did it fit?'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review-images', verbose_name='Customer Photo'),
        ),
    ]
