# Generated by Django 3.2.3 on 2026-07-23 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0056_review_photo_fit_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('event_type', models.CharField(choices=[('view', 'Viewed'), ('add_to_cart', 'Added to cart'), ('purchase', 'Purchased')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['product', 'event_type', 'created_at'], name='store_produ_product_70771a_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['user', 'created_at'], name='store_produ_user_id_129e11_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['session_key', 'created_at'], name='store_produ_session_b986f6_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['created_at'], name='store_produ_created_32a06e_idx'),
        ),
    ]
