# Generated by Django 3.2.3 on 2026-07-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_product_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='task_type',
            field=models.CharField(choices=[('telegram_product_post', 'Telegram product post'), ('telegram_order_notify', 'Telegram order notification'), ('telegram_signup_notify', 'Telegram signup notification'), ('ai_enrich_draft', 'AI draft enrichment'), ('customer_order_confirm', 'Customer order confirmation'), ('customer_order_status', 'Customer order status update'), ('customer_restock_notify', 'Customer restock alert'), ('customer_abandoned_cart', 'Customer abandoned-cart nudge'), ('customer_broadcast', 'Customer broadcast message'), ('wishlist_sale_notify', 'Wishlist sale alert')], max_length=40),
        ),
    ]
