# Generated by Django 3.2.3 on 2026-09-03 20:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0058_broadcast_wishlist_sale_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Order Number')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('claim_token', models.CharField(default=store.models._new_claim_token, editable=False, max_length=48, unique=True)),
                ('contact', models.JSONField(blank=True, default=dict, help_text='full_name/phone/email/city/address snapshot taken at checkout')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=30)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on delivery'), ('chapa', 'Paid online (Chapa)')], default='cod', max_length=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Pay on delivery'), ('pending', 'Awaiting online payment'), ('paid', 'Paid'), ('failed', 'Payment failed')], default='unpaid', max_length=12)),
                ('payment_reference', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_tracked', models.BooleanField(default=False, help_text='GA4 purchase event already emitted for this order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=120)),
                ('normalized_term', models.CharField(db_index=True, max_length=120)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='productreview',
            name='unique_user_product_review',
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Unique search-result snippet for this brand page (falls back to the description).', max_length=320, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Unique search-result snippet for this collection page (falls back to the description).', max_length=320, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_guide',
            field=models.TextField(blank=True, help_text="Shown on every product in this collection. One size per line, e.g. 'M — chest 96-100 cm, waist 80-84 cm'. Add a blank line and free text for fit advice.", verbose_name='Size Guide'),
        ),
        migrations.AddField(
            model_name='order',
            name='review_invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Tokenised review-invite link issued when the line is delivered.', max_length=48),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False, help_text='Units were returned to inventory when this line was cancelled.'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.TextField(blank=True, help_text="Garment measurements, one size per line (e.g. 'M — length 70 cm, chest 104 cm'). Overrides the collection size guide.", verbose_name='Measurements'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Verified Purchase'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='store.order', verbose_name='Delivered order line'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reviewer_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Reviewer Name'),
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='task_type',
            field=models.CharField(choices=[('telegram_product_post', 'Telegram product post'), ('telegram_order_notify', 'Telegram order notification'), ('telegram_signup_notify', 'Telegram signup notification'), ('ai_enrich_draft', 'AI draft enrichment'), ('customer_order_confirm', 'Customer order confirmation'), ('customer_order_status', 'Customer order status update'), ('customer_restock_notify', 'Customer restock alert'), ('customer_abandoned_cart', 'Customer abandoned-cart nudge'), ('customer_broadcast', 'Customer broadcast message'), ('wishlist_sale_notify', 'Wishlist sale alert'), ('customer_order_messages', 'Customer order SMS/email'), ('customer_review_invite', 'Customer review invite')], max_length=40),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product_review_when_user'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='store.ordergroup', verbose_name='Order'),
        ),
        migrations.AddIndex(
            model_name='ordergroup',
            index=models.Index(fields=['user', 'created_at'], name='store_order_user_id_dd4216_idx'),
        ),
        migrations.AddIndex(
            model_name='ordergroup',
            index=models.Index(fields=['session_key', 'created_at'], name='store_order_session_b82c39_idx'),
        ),
    ]
