# Generated by Django 3.2.3 on 2026-09-05 13:21
#
# Colour variants: one ProductColorGroup per garment, one Product per colour.
# The field must exist before the index that uses it, so AddField comes first
# (makemigrations emitted them the other way round).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_backfill_order_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Style name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colour group',
                'verbose_name_plural': 'Colour groups',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_group',
            field=models.ForeignKey(blank=True, help_text="Other colours of the same garment. Managed from the product editor's Colours panel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.productcolorgroup', verbose_name='Colour group'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['color_group', 'is_active'], name='store_produ_color_g_cac804_idx'),
        ),
    ]
